name: vote
description: "Vote App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^17.0.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  supabase: ^2.10.0
  get_it: ^9.1.1
  injectable: ^2.7.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  app_theme:
    path: packages/theme
  app_component:
    path: packages/component
  app_env:
    path: packages/env

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.4
  freezed: ^3.2.3
  json_serializable: ^6.7.1
  injectable_generator: ^2.9.1

flutter:
  uses-material-design: true
  generate: true
