name: app_component
description: Reusable UI components for Vote App
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  app_theme:
    path: ../theme

dev_dependencies:
  flutter_lints: ^5.0.0
