name: app_env
description: Environment config for Vote App (Envied)
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  envied: ^1.3.2

dev_dependencies:
  flutter_lints: ^6.0.0
  build_runner: ^2.10.4
  envied_generator: ^1.3.2
